# Generated by Django 5.1.6 on 2025-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="height_cm",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="weight_kg",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allergies",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
