# Generated by Django 5.1.6 on 2025-11-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0002_remove_userprofile_height_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=50,
            ),
        ),
    ]
