# Generated by Django 5.2 on 2025-11-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_dailyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
