# Generated by Django 5.2 on 2025-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_userprofile_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
